### ISSUE TITLE
Code license

### ISSUE THREAD

**Issue by Trilarion** [bylexus/sensitive-js#1]
The readme file contains a section about potential copyright problems with some artwork but it does not say anything about the license of the code. What is the license of the code and could information about it be added to the repository?

**Comment by bylexus** [comment]
Hi,
Thanks for mentioning this. The code can be used in any way you like. I did not include a license info as it's just the default copyright license. I will add a notice in the readme.
So I give permission to use it in any way you like, except for commercial usage.
